"""add name column to promotions table

Revision ID: 18d2cd84c53a
Revises: c6a1506b7309
Create Date: 2026-01-18 18:41:04.826543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18d2cd84c53a'
down_revision: Union[str, Sequence[str], None] = 'c6a1506b7309'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promotions', sa.Column('name', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('promotions', 'name')
    # ### end Alembic commands ###
