"""add image fields to restaurant

Revision ID: 782833f46426
Revises: 50fd3750f4be
Create Date: 2026-01-15 06:27:48.514683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '782833f46426'
down_revision: Union[str, Sequence[str], None] = '50fd3750f4be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('business_license_image', sa.String(length=255), nullable=True))
    op.add_column('restaurants', sa.Column('food_safety_certificate_image', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'food_safety_certificate_image')
    op.drop_column('restaurants', 'business_license_image')
    # ### end Alembic commands ###
