"""change start_date and end_date to date type

Revision ID: a383efc05b39
Revises: 18d2cd84c53a
Create Date: 2026-01-18 18:46:34.738005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a383efc05b39'
down_revision: Union[str, Sequence[str], None] = '18d2cd84c53a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('promotions', 'start_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               nullable=False)
    op.alter_column('promotions', 'end_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('promotions', 'end_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('promotions', 'start_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
