"""Initial migration

Revision ID: 1aa6c646e0ab
Revises: 
Create Date: 2026-01-16 18:12:39.012621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1aa6c646e0ab'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_order_items_order_id'), table_name='order_items')
    op.drop_constraint(op.f('order_items_order_id_fkey'), 'order_items', type_='foreignkey')
    op.create_foreign_key(None, 'order_items', 'orders', ['order_id'], ['id'])
    op.drop_index(op.f('idx_orders_driver_id'), table_name='orders')
    op.drop_index(op.f('idx_orders_restaurant_id'), table_name='orders')
    op.drop_index(op.f('idx_orders_status'), table_name='orders')
    op.drop_index(op.f('idx_orders_user_id'), table_name='orders')
    op.create_index(op.f('ix_orders_driver_id'), 'orders', ['driver_id'], unique=False)
    op.create_index(op.f('ix_orders_restaurant_id'), 'orders', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.drop_index(op.f('idx_profiles_email'), table_name='profiles')
    op.drop_index(op.f('idx_profiles_phone'), table_name='profiles')
    op.drop_constraint(op.f('profiles_email_key'), 'profiles', type_='unique')
    op.drop_constraint(op.f('profiles_phone_key'), 'profiles', type_='unique')
    op.create_index(op.f('ix_profiles_email'), 'profiles', ['email'], unique=True)
    op.create_index(op.f('ix_profiles_phone'), 'profiles', ['phone'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profiles_phone'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_email'), table_name='profiles')
    op.create_unique_constraint(op.f('profiles_phone_key'), 'profiles', ['phone'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('profiles_email_key'), 'profiles', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_profiles_phone'), 'profiles', ['phone'], unique=False)
    op.create_index(op.f('idx_profiles_email'), 'profiles', ['email'], unique=False)
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_restaurant_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_driver_id'), table_name='orders')
    op.create_index(op.f('idx_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_index(op.f('idx_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('idx_orders_restaurant_id'), 'orders', ['restaurant_id'], unique=False)
    op.create_index(op.f('idx_orders_driver_id'), 'orders', ['driver_id'], unique=False)
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.create_foreign_key(op.f('order_items_order_id_fkey'), 'order_items', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    # ### end Alembic commands ###
