"""remove latitude longitude fields from restaurant

Revision ID: 0f5ac9437597
Revises: 782833f46426
Create Date: 2026-01-15 06:37:06.588787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f5ac9437597'
down_revision: Union[str, Sequence[str], None] = '782833f46426'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'latitude')
    op.drop_column('restaurants', 'longitude')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('longitude', sa.NUMERIC(precision=11, scale=8), autoincrement=False, nullable=True))
    op.add_column('restaurants', sa.Column('latitude', sa.NUMERIC(precision=10, scale=8), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
