@baseUrl = http://localhost:8003
@adminToken = {{authresponse.response.body.access_token}}
### 1️⃣ Root
GET {{baseUrl}}/
Accept: application/json

### 3️⃣ Login
# @name authresponse
POST {{baseUrl}}/auth/login/admin
Content-Type: application/json

{
  "email": "admin@grab.com",
  "password": "123"
}
###
GET {{baseUrl}}/auth/me
Authorization: Bearer {{adminToken}}
Accept: application/json

### Get all users
GET {{baseUrl}}/admin/users
Authorization: Bearer {{adminToken}}

### Get users with role = user
GET {{baseUrl}}/admin/users?role=user
Authorization: Bearer {{adminToken}}

### Get users with role = seller
GET {{baseUrl}}/admin/users?role=seller
Authorization: Bearer {{adminToken}}

### Get users with role = shipper
GET {{baseUrl}}/admin/users?role=shipper
Authorization: Bearer {{adminToken}}

###
PATCH {{baseUrl}}/admin/users/6/status
Authorization: Bearer {{adminToken}}

{
  "status": "active"
}